webapp/models.py
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import func
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import AnonymousUserMixin
from flask_mongoengine import MongoEngine
db = SQLAlchemy()
mongo = MongoEngine()
roles = db.Table(
    'role_users',
    db.Column('user_name',db.String(80),db.ForeignKey('users.username')),
    db.Column('role_id',db.Integer,db.ForeignKey('role.id'))

)
class stock_basics(db.Model):
    __tablename__='stock_basics'
    trade_code = db.Column(db.String(20),primary_key=True)
    sec_name = db.Column(db.String(20))
    ipo_date = db.Column(db.DateTime())
    exch_city = db.Column(db.String(20))
    industry_gics = db.Column(db.String(20))
    concept = db.Column(db.String(200))
    curr = db.Column(db.String(20))
    fiscaldate = db.Column(db.String(20))
    auditor = db.Column(db.String(200))
    province = db.Column(db.String(20))
    city = db.Column(db.String(20))
    founddate = db.Column(db.DateTime())
    nature1 = db.Column(db.String(20))
    boardchairmen = db.Column(db.String(20))
    holder_controller = db.Column(db.String(20))
    website = db.Column(db.String(10000))
    phone = db.Column(db.String(200))
    majorproducttype = db.Column(db.String(200))
    majorproductname = db.Column(db.String(2000))

class users(db.Model):
    __tablename__='users'
    username = db.Column(db.String(20),primary_key=True)
    password = db.Column(db.String(45))
    roles = db.relationship(
        'Role',
        secondary=roles,
        backref=db.backref('users',lazy='dynamic')
    )
    def set_password(self,password):
        self.password = generate_password_hash(password)
    def check_password(self,password):
        return check_password_hash(self.password,password)
    def is_authenticated(self):
        if isinstance(self,AnonymousUserMixin):
            return False
        else:
            return True
    def is_active(self):
        return True
    def is_anonymous(self):
        if isinstance(self,AnonymousUserMixin):
            return True
        else:
            return False
    def get_id(self):
        return unicode(self.username)
class Role(db.Model):
    id=db.Column(db.Integer(),primary_key=True)
    name = db.Column(db.String(80),unique=True)
    description = db.Column(db.String(255))

available_roles = ('admin','finance_analyst','default')
class User(mongo.Document):
    username = mongo.StringField(required=True)
    password = mongo.StringField(required=True)
    roles = mongo.ListField(mongo.StringField(choices=available_roles))
    def set_password(self,password):
        self.password = generate_password_hash(password)
    def check_password(self,password):
        return check_password_hash(self.password,password)
    def is_authenticated(self):
        if isinstance(self,AnonymousUserMixin):
            return False
        else:
            return True

    def is_active(self):
        return True
    def is_anonymous(self):
        if isinstance(self,AnonymousUserMixin):
            return True
        else:
            return False
    def get_id(self):
        return unicode(self.username)
class stock_basicsm(mongo.Document):
    trade_code = mongo.StringField()
    SEC_NAME = mongo.StringField()
    IPO_DATE = mongo.DateTimeField()
    EXCH_CITY = mongo.StringField()
    INDUSTRY_GICS = mongo.StringField()
    CONCEPT = mongo.StringField()
    CURR = mongo.StringField()
    FISCALDATE = mongo.StringField()
    AUDITOR = mongo.StringField()
    PROVINCE = mongo.StringField()
    CITY = mongo.StringField()
    FOUNDDATE = mongo.DateTimeField()
    NATURE1 = mongo.StringField()
    BOARDCHAIRMEN = mongo.StringField()
    HOLDER_CONTROLLER = mongo.StringField()
    WEBSITE = mongo.StringField()
    PHONE = mongo.StringField()
    MAJORPRODUCTTYPE = mongo.StringField()
    MAJORPRODUCTNAME = mongo.StringField()
    meta = {'collection':'stock_basics'}

webapp/forms.py
from flask_wtf import Form
from wtforms import StringField, TextAreaField,PasswordField,BooleanField
from wtforms.validators import DataRequired,Length,EqualTo,URL
from models import users
class CodeForm(Form):
    code = StringField('Stock Code',validators=[DataRequired()])
class LoginForm(Form):
    username = StringField('Username',[DataRequired(),Length(max=20)])
    password = PasswordField('Password',[DataRequired()])
    remember = BooleanField("Remember Me")
    def validate(self):
        check_validate = super(LoginForm,self).validate()
        if not check_validate:
            return False
        user = users.query.filter_by(username = self.username.data).first()
        if not user:
            self.username.errors.append('Invalid username or password')
            return False
        if not user.check_password(self.password.data):
            self.username.errors.append('Invalid username or password')
            return False
        return True
class RegisterForm(Form):
    username = StringField('Username',[DataRequired(),Length(max=255)])
    password = PasswordField('Password',[DataRequired()])
    confirm = PasswordField('Confirm Password',[DataRequired(),EqualTo('password')])
    def validate(self):
        check_validate = super(RegisterForm,self).validate()
        if not check_validate:
            return False
        user = users.query.filter_by(username = self.username.data).first()
        if user:
            self.username.errors.append("Users with that name already exists")
            return False
        return True

webapp/__init__.py
from flask import Flask,redirect,url_for,render_template
from flask_principal import identity_loaded,UserNeed,RoleNeed
from config import DevConfig
from controllers.stock import stock_blueprint
from controllers.main import main_blueprint
from controllers.stock_solo import stocksolo_blueprint
from forms import CodeForm
from datetime import datetime
from extensions import login_manager,principals
from models import db,mongo
from flask_login import current_user



def create_app(object_name):
    app = Flask(__name__)
    app.config.from_object(DevConfig)
    #db.init_app(app)
    # @app.route('/')
    # def index():
    #     return redirect(url_for('blog.home'))
    login_manager.init_app(app)
    principals.init_app(app)
    db.init_app(app)
    mongo.init_app(app)
    app.register_blueprint(stock_blueprint)
    app.register_blueprint(main_blueprint)
    app.register_blueprint(stocksolo_blueprint)
    @identity_loaded.connect_via(app)
    def on_identity_loaded(sender,identity):
        identity.user = current_user
        if hasattr(current_user,"username"):
            identity.provides.add(UserNeed(current_user.username))
        if hasattr(current_user,'roles'):
            for role in current_user.roles:
                identity.provides.add(RoleNeed(role))
    return app

webapp/controllers/main.py
from flask import Blueprint,redirect,url_for,flash,render_template
from webapp.forms import LoginForm,RegisterForm
from webapp.models import User,mongo
from flask_login import login_user,login_required,logout_user,current_user,current_app
from flask_principal import Identity,AnonymousIdentity,identity_changed
main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='../templates/main'
)

@main_blueprint.route('/')
def index():
    return redirect(url_for('main.login'))

@main_blueprint.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()
        login_user(user,remember=form.remember.data)
        identity_changed.send(
            current_app._get_current_object(),
            identity=Identity(user.username)
        )
        flash("You have been logged in",category="success")
        return redirect(url_for('stock.home'))
    return render_template('main/login.html',form=form)

@main_blueprint.route('/register',methods=['GET','POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        new_user = User()
        new_user.username = form.username.data
        new_user.set_password(form.password.data)
        new_user.save()
        flash(
            "Your user has been created, please login",
            category="success"
        )
        return redirect(url_for('.login'))
    return render_template("main/register.html",form=form)
@main_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    identity_changed.send(
        current_app._get_current_object(),
        identity=AnonymousIdentity()
    )
    return redirect(url_for('main.login'))

webapp/controllers/stock.py
from flask import Blueprint,redirect,render_template,url_for
from os import path
from webapp.extensions import finance_analyst_permission
from flask_principal import Permission,UserNeed,RoleNeed
from flask_login import login_required,current_user
stock_blueprint = Blueprint(
    'stock',
    __name__,
    template_folder=path.join(path.pardir,'templates','stock'),
    url_prefix="/stock"
)
@stock_blueprint.route('/',methods=('GET','POST'))
@login_required
def home():
    roles = current_user.roles


    return render_template("stock/home.html",current_user=current_user,roles=roles)

webapp/controllers/stock_solo.py
from flask import Blueprint,redirect,render_template,url_for
from os import path
from webapp.models import stock_basicsm
from webapp.forms import CodeForm
from flask_login import login_required,current_user
from webapp.extensions import finance_analyst_permission
stocksolo_blueprint = Blueprint(
    'stock_solo',
    __name__,
    template_folder=path.join(path.pardir,'templates','stock_solo'),
    url_prefix="/stock_solo"
)
@stocksolo_blueprint.route('/',methods=('GET','POST'))
@stocksolo_blueprint.route('/<string:trade_code>',methods=('GET','POST'))
@login_required
@finance_analyst_permission.require(http_exception=403)
def home(trade_code='000001.SZ'):
    trade_code=trade_code
    form = CodeForm()
    if form.validate_on_submit():
        trade_code = form.code.data
        return redirect(url_for('stock_solo.home',current_user=current_user,trade_code=trade_code))
    stock = stock_basicsm.objects(trade_code=trade_code).first()
    return render_template("stock_solo/stock_solo_home.html",current_user=current_user,form=form,stock = stock)

webapp/templates/base.html
<html>
<head>
<meta charset='utf-8'>
<script type="text/javascript" src="http://www.francescomalagrino.com/BootstrapPageGenerator/3/js/jquery-2.0.0.min.js"></script>
<script type="text/javascript" src="http://www.francescomalagrino.com/BootstrapPageGenerator/3/js/jquery-ui"></script>
<link href="https://cdn.bootcss.com/bootstrap/3.1.1/css/bootstrap-rtl.min.css" rel="stylesheet" media="screen">
<script type="text/javascript" src="https://cdn.bootcss.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</head>
<style>
    /* BOOTSTRAP 3.x GLOBAL STYLES
-------------------------------------------------- */
body {
  padding-bottom: 40px;
  color: #5a5a5a;
}



/* CUSTOMIZE THE NAVBAR
-------------------------------------------------- */

/* Special class on .container surrounding .navbar, used for positioning it into place. */
.navbar-wrapper {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  z-index: 10;
}



/* CUSTOMIZE THE CAROUSEL
-------------------------------------------------- */

/* Carousel base class */
.carousel {
  margin-bottom: 60px;
}
/* Since positioning the image, we need to help out the caption */
.carousel-caption {
  z-index: 1;
}

/* Declare heights because of positioning of img element */
.carousel .item {
  height: 400px;
  background-color:#555;
}
.carousel img {
  position: absolute;
  top: 0;
  left: 0;
  min-height: 400px;
}



/* MARKETING CONTENT
-------------------------------------------------- */

/* Pad the edges of the mobile views a bit */
.marketing {
  padding-left: 15px;
  padding-right: 15px;
}

/* Center align the text within the three columns below the carousel */
.marketing .col-lg-4 {
  text-align: center;
  margin-bottom: 20px;
}
.marketing h2 {
  font-weight: normal;
}
.marketing .col-lg-4 p {
  margin-left: 10px;
  margin-right: 10px;
}


/* Featurettes
------------------------- */

.featurette-divider {
  margin: 80px 0; /* Space out the Bootstrap <hr> more */
}
.featurette {
  padding-top: 120px; /* Vertically center images part 1: add padding above and below text. */
  overflow: hidden; /* Vertically center images part 2: clear their floats. */
}
.featurette-image {
  margin-top: -120px; /* Vertically center images part 3: negative margin up the image the same amount of the padding to center it. */
}

/* Give some space on the sides of the floated elements so text doesn't run right into it. */
.featurette-image.pull-left {
  margin-right: 40px;
}
.featurette-image.pull-right {
  margin-left: 40px;
}

/* Thin out the marketing headings */
.featurette-heading {
  font-size: 50px;
  font-weight: 300;
  line-height: 1;
  letter-spacing: -1px;
}



/* RESPONSIVE CSS
-------------------------------------------------- */

@media (min-width: 768px) {

  /* Remve the edge padding needed for mobile */
  .marketing {
    padding-left: 0;
    padding-right: 0;
  }

  /* Navbar positioning foo */
  .navbar-wrapper {
    margin-top: 20px;
    margin-bottom: -90px; /* Negative margin to pull up carousel. 90px is roughly margins and height of navbar. */
  }
  /* The navbar becomes detached from the top, so we round the corners */
  .navbar-wrapper .navbar {
    border-radius: 4px;
  }

  /* Bump up size of carousel content */
  .carousel-caption p {
    margin-bottom: 20px;
    font-size: 21px;
    line-height: 1.4;
  }

}

</style>
<body>
<div class="navbar-wrapper">
  <div class="container">
    <div class="navbar navbar-inverse navbar-static-top">

        <div class="navbar-header">
	    <a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </a>
        <a class="navbar-brand" href="#">Bootstrap 3</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="http://www.bootply.com" target="ext">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div>

    </div>
  </div><!-- /container -->
</div><!-- /navbar wrapper -->


<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <img src="/assets/example/bg_suburb.jpg" style="width:100%" class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h1>Bootstrap 3 Carousel Layout</h1>
          <p></p>
          <p><a class="btn btn-lg btn-primary" href="http://getbootstrap.com">Learn More</a>
        </p>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="http://lorempixel.com/2000/600/abstract/1" class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h1>Changes to the Grid</h1>
          <p>Bootstrap 3 still features a 12-column grid, but many of the CSS class names have completely changed.</p>
          <p><a class="btn btn-large btn-primary" href="#">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="http://placehold.it/1500X500" class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h1>Percentage-based sizing</h1>
          <p>With "mobile-first" there is now only one percentage-based grid.</p>
          <p><a class="btn btn-large btn-primary" href="#">Browse gallery</a></p>
        </div>
      </div>
    </div>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>
</div>
<!-- /.carousel -->


<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

  <!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="col-md-4 text-center">
      <img class="img-circle" src="http://placehold.it/140x140">
      <h2>Mobile-first</h2>
      <p>Tablets, phones, laptops. The new 3 promises to be mobile friendly from the start.</p>
      <p><a class="btn btn-default" href="#">View details »</a></p>
    </div>
    <div class="col-md-4 text-center">
      <img class="img-circle" src="http://placehold.it/140x140">
      <h2>One Fluid Grid</h2>
      <p>There is now just one percentage-based grid for Bootstrap 3. Customize for fixed widths.</p>
      <p><a class="btn btn-default" href="#">View details »</a></p>
    </div>
    <div class="col-md-4 text-center">
      <img class="img-circle" src="http://placehold.it/140x140">
      <h2>LESS is More</h2>
      <p>Improved support for mixins make the new Bootstrap 3 easier to customize.</p>
      <p><a class="btn btn-default" href="#">View details »</a></p>
    </div>
  </div><!-- /.row -->


  <!-- START THE FEATURETTES -->

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-right" src="http://placehold.it/512">
    <h2 class="featurette-heading">Responsive Design. <span class="text-muted">It'll blow your mind.</span></h2>
    <p class="lead">In simple terms, a responsive web design figures out what resolution of device it's being served on. Flexible grids then size correctly to fit the screen.</p>
  </div>

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-left" src="http://placehold.it/512">
    <h2 class="featurette-heading">Smaller Footprint. <span class="text-muted">Lightweight.</span></h2>
    <p class="lead">The new Bootstrap 3 promises to be a smaller build. The separate Bootstrap base and responsive.css files have now been merged into one. There is no more fixed grid, only fluid.</p>
  </div>

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-right" src="http://placehold.it/512">
    <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Flatness.</span></h2>
    <p class="lead">A big design trend for 2013 is "flat" design. Gone are the days of excessive gradients and shadows. Designers are producing cleaner flat designs, and Bootstrap 3 takes advantage of this minimalist trend.</p>
  </div>

  <hr class="featurette-divider">

  <!-- /END THE FEATURETTES -->


  <!-- FOOTER -->
  <footer>
    <p class="pull-right"><a href="#">Back to top</a></p>
    <p>This Bootstrap layout is compliments of Bootply. · <a href="http://www.bootply.com/62603">Edit on Bootply.com</a></p>
  </footer>

</div><!-- /.container -->
</body>

webapp/templates/stock_base.html
<html>
<head>
<meta charset='utf-8'>
<script type="text/javascript" src="{{ url_for('static',filename='js/jquery-2.0.0.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='js/jquery-ui') }}"></script>
<link href="{{ url_for('static',filename='css/bootstrap-combined.min.css') }}" rel="stylesheet" media="screen">
<script type="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>
{#    <script type="text/javascript" src="http://www.francescomalagrino.com/BootstrapPageGenerator/3/js/jquery-2.0.0.min.js"></script>#}
{#    <script type="text/javascript" src="http://www.francescomalagrino.com/BootstrapPageGenerator/3/js/jquery-ui"></script>#}
{#    <link href="http://www.francescomalagrino.com/BootstrapPageGenerator/3/css/bootstrap-combined.min.css" rel="stylesheet" media="screen">#}
{#    <script type="text/javascript" src="http://www.francescomalagrino.com/BootstrapPageGenerator/3/js/bootstrap.min.js"></script>#}
</head>
<body>

<div class="container-fluid" id="LG" style="width: 90%;margin: auto;margin-top: 1%;">

    <div class="navbar">
        <div class="navbar-inner" >
            <div class="container-fluid">
                <a class="btn btn-navbar" data-target=".navbar-responsive-collapse" data-toggle="collapse"></a> <a class="brand" href="#"><font style="font-weight: bold">金融投资分析系统</font></a>
                <div class="nav-collapse collapse navbar-responsive-collapse">
                    <ul class="nav nav-pills">
                                {% block current_user %}{% endblock %}
                            </ul>

                    <ul class="nav pull-right">
								<li class="divider-vertical">
								</li>
								<li class="dropdown">
									<a class="dropdown-toggle" data-toggle="dropdown" href="#">账户设置</a>
									<ul class="dropdown-menu">
										<li>
											<a href="#">登录</a>
										</li>
										<li>
											<a href="#">设置</a>
										</li>
										<li>
											<a href="#">其他</a>
										</li>
										<li class="divider">
										</li>
										<li>
											<a href="{{ url_for('main.logout') }}">注销账户</a>
										</li>
									</ul>
								</li>
							</ul>
                </div>
            </div>
        </div>
    </div>

    <div style="margin-top: 1px">
        {% block body %}{% endblock %}
    </div>

</div>
</body>
</html>